# Filename: docker-compose.yml

version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nextjs_frontend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://django_backend_vt:8000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev